# Generated by Django 2.0.5 on 2019-03-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='Customer',
        ),
    ]
