# Generated by Django 2.0.5 on 2019-03-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
    ]
