# Generated by Django 2.0.5 on 2019-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20190320_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
    ]
