# Generated by Django 2.0.5 on 2019-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_customer_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='template_name',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
