# Generated by Django 2.0.5 on 2019-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20190320_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='template_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
