# Generated by Django 2.0.5 on 2019-03-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20190320_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='template_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='assessment.Template', verbose_name='Template'),
        ),
    ]
