# Generated by Django 2.0.5 on 2019-03-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20190321_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='assessment.Template', verbose_name='Template'),
        ),
    ]
